apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrations
  namespace: animal-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: flyway/flyway@sha256:6f913eb7df2cfc1c51c93034c6e6eae35ab0cd8dd1c3d0cdd11b9f6c1cf64cc1 # 9.22.0 arm/v7
        command: ["flyway", "-baselineOnMigrate=true", "migrate"]
        env:
        - name: FLYWAY_URL
          value: jdbc:postgresql://postgres:5432/$(POSTGRES_DATABASE)
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DATABASE
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql
      volumes:
      - name: migrations
        configMap:
          name: postgres-migrations
      restartPolicy: Never
  backoffLimit: 1
