apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: animal-api
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: migrate
          image: postgres:13
          command: ["sh", "-c"]
          args:
            [
              "for file in $(ls /migrations/*.sql | sort); do echo Running migration: $file; psql -U $POSTGRES_USER -d $POSTGRES_DB -f $file; done"
            ]
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: migrations
          gitRepo:
            repository: https://github.com/its-haze/animal-api-gitops
            revision: master
            directory: migrations
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
