apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrations
  namespace: animal-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: flyway/flyway@sha256:6f913eb7df2cfc1c51c93034c6e6eae35ab0cd8dd1c3d0cdd11b9f6c1cf64cc1
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting for PostgreSQL to be ready..."
            while ! nc -z postgres 5432; do
              sleep 1
            done
            flyway -baselineOnMigrate=true migrate -url=jdbc:postgresql://postgres:5432/$(POSTGRES_DB) -user=$(POSTGRES_USER) -password=$(POSTGRES_PASSWORD)
        envFrom:
          - secretRef:
              name: postgres-secrets
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql
      volumes:
      - name: migrations
        configMap:
          name: postgres-migrations
      restartPolicy: Never
  backoffLimit: 1
