apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrations
  namespace: animal-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: ghcr.io/animal-facts/animal_db_migration:v0.0.1
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting for PostgreSQL to be ready..."
            while ! pg_isready -h postgres -p 5432 -U $(POSTGRES_USER) -d $(POSTGRES_DB); do
              echo "PostgreSQL is not ready yet. Retrying in 5 seconds..."
              sleep 5
            done
            echo "PostgreSQL is ready. Running migrations..."
            flyway -baselineOnMigrate=true migrate -url=jdbc:postgresql://postgres:5432/$(POSTGRES_DB) -user=$(POSTGRES_USER) -password=$(POSTGRES_PASSWORD)
        envFrom:
          - secretRef:
              name: postgres-secrets
      restartPolicy: Never
  backoffLimit: 1
