apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: postgres:13
          command: ["sh", "-c"]
          args:
            [
              "for file in $(ls /migrations/*.sql | sort); do \
              echo 'Running migration: $file'; \
              psql -h postgres -U admin -d animaldb -f $file; \
              done"
            ]
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      restartPolicy: OnFailure
      volumes:
        - name: migrations
          hostPath:
            path: ./migrations
            type: Directory
