apiVersion: v1
kind: Service
metadata:
  name: animal-api
  namespace: animal-api
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000 # Default port that FastAPI listens on.
    nodePort: 30080 # You will access the API on this port.
  selector:
    app: animal-api
