apiVersion: v1
kind: Service
metadata:
  name: animal-api
  namespace: animal-api
spec:
  type: ClusterIP # Internal Service, but will be exposed by Ingress.
  ports:
  - port: 8000
    targetPort: 8000 # Default port that FastAPI listens on.
  selector:
    app: animal-api
